### ISSUE TITLE
你好，可以共享下数据集吗？

### ISSUE THREAD

**Issue by yuwl798180** [baidu/information-extraction#13]
你好，我最近刚看到这个比赛，很遗憾比赛已经结束了。

但是我这个比赛的数据集的质量很棒，很让我羡慕。

请问是否还可以共享下数据集？我是学生，做科研使用。

谢谢！

**Comment by hweidream** [comment]
你好，信息抽取数据集会在6月底发布在百度ai开放平台上，http://ai.baidu.com/broad/download

**Comment by pedrogao** [comment]
跪等。。。

**Comment by yuwl798180** [comment]
@hweidream  
你好，已经7月，数据还是不可下载状态。
真心希望可以下载到数据。
抽取三元组的中文数据集太少了，若是百度能贡献出来，让国内研究者做研究，对百度也是极大的宣传。
谢谢

**Comment by hweidream** [comment]
@yuwl798180 你好！之前因为排期等原因暂未发布，7月份会公开下载的，请放心。

**Comment by benkang-chen** [comment]
七月9号，打卡

**Comment by yuwl798180** [comment]
别打卡了，我已经对baidu这个公司彻底不抱希望了。。
等8月份时，估计还是不会放出数据集。
继续把上面的理由再复制一次，只是7改成8

**Comment by hweidream** [comment]
> 别打卡了，我已经对baidu这个公司彻底不抱希望了。。
> 等8月份时，估计还是不会放出数据集。
> 继续把上面的理由再复制一次，只是7改成8

已经于7.12在百度ai开放平台上开放下载了，http://ai.baidu.com/broad/download

**Comment by benkang-chen** [comment]
可以了


 
---原始邮件---
发件人: "hweidream"<notifications@github.com>
发送时间: 2019年7月20日(星期六) 上午10:45
收件人: "baidu/information-extraction"<information-extraction@noreply.github.com>;
抄送: "benkang-chen"<benkang.chen@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [baidu/information-extraction] 你好，可以共享下数据集吗？ (#13)


 
别打卡了，我已经对baidu这个公司彻底不抱希望了。。
 等8月份时，估计还是不会放出数据集。
 继续把上面的理由再复制一次，只是7改成8
  
已经于7.12在百度ai开放平台上开放下载了，http://ai.baidu.com/broad/download
